name: Cleanup AWS Resources

on:
  workflow_dispatch:
    inputs:
      confirm_deletion:
        description: 'Type "DELETE" to confirm resource deletion'
        required: true
        default: ''
        type: string

env:
  AWS_REGION: eu-central-1
  FUNCTION_NAME: mcp-server
  API_GATEWAY_NAME: mcp-server-api
  
  # IAM Resources
  ROLE_NAME: mini-mcp-server-role
  API_POLICY_NAME: mcp-server-api-policy
  S3_POLICY_NAME: mcp-server-s3-policy
  
  # API Gateway Configuration
  API_STAGE_NAME: prod
  MCP_ENDPOINT_PATH: /mcp
  HEALTH_ENDPOINT_PATH: /health
  HTTP_METHOD: POST

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate confirmation
        run: |
          if [ "${{ github.event.inputs.confirm_deletion }}" != "DELETE" ]; then
            echo "❌ Deletion not confirmed. Please type 'DELETE' to confirm."
            exit 1
          fi
          echo "✅ Deletion confirmed. Proceeding with cleanup..."

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Delete Lambda Permissions
        run: |
          echo "🗑️ Deleting Lambda permissions for: ${{ env.FUNCTION_NAME }}"
          if aws lambda get-function --function-name ${{ env.FUNCTION_NAME }} >/dev/null 2>&1; then
            # Get all policy statements and remove API Gateway permissions
            POLICY=$(aws lambda get-policy --function-name ${{ env.FUNCTION_NAME }} --query 'Policy' --output text 2>/dev/null || echo '{}')
            if [ "$POLICY" != "{}" ]; then
              echo "$POLICY" | jq -r '.Statement[] | select(.Principal.Service == "apigateway.amazonaws.com") | .Sid' | while read statement_id; do
                if [ ! -z "$statement_id" ]; then
                  echo "Removing permission: $statement_id"
                  aws lambda remove-permission --function-name ${{ env.FUNCTION_NAME }} --statement-id "$statement_id" || echo "Permission $statement_id not found"
                fi
              done
              echo "✅ Lambda permissions cleaned up"
            else
              echo "ℹ️ No Lambda permissions found"
            fi
          else
            echo "ℹ️ Lambda function not found, skipping permissions cleanup..."
          fi

      - name: Delete Lambda Function
        run: |
          echo "🗑️ Deleting Lambda function: ${{ env.FUNCTION_NAME }}"
          if aws lambda get-function --function-name ${{ env.FUNCTION_NAME }} >/dev/null 2>&1; then
            aws lambda delete-function --function-name ${{ env.FUNCTION_NAME }}
            echo "✅ Lambda function deleted successfully"
          else
            echo "ℹ️ Lambda function not found, skipping..."
          fi

      - name: Delete API Gateway
        run: |
          echo "🗑️ Deleting API Gateway: ${{ env.API_GATEWAY_NAME }}"
          API_ID=$(aws apigateway get-rest-apis --query 'items[?name==`${{ env.API_GATEWAY_NAME }}`].[id]' --output text | head -1)
          
          if [ ! -z "$API_ID" ] && [ "$API_ID" != "None" ]; then
            aws apigateway delete-rest-api --rest-api-id $API_ID
            echo "✅ API Gateway deleted successfully (ID: $API_ID)"
          else
            echo "ℹ️ API Gateway not found, skipping..."
          fi

      - name: Detach IAM Role Policies
        run: |
          echo "🔓 Detaching IAM role policies: ${{ env.ROLE_NAME }}"
          if aws iam get-role --role-name ${{ env.ROLE_NAME }} >/dev/null 2>&1; then
            # Get account ID for policy ARN
            ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
            
            # Detach basic execution role
            aws iam detach-role-policy \
              --role-name ${{ env.ROLE_NAME }} \
              --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole || echo "Basic execution policy not attached"
            
            # Detach custom S3 policy
            aws iam detach-role-policy \
              --role-name ${{ env.ROLE_NAME }} \
              --policy-arn arn:aws:iam::$ACCOUNT_ID:policy/${{ env.S3_POLICY_NAME }} || echo "S3 policy not attached"
            
            # Detach custom API Gateway policy
            aws iam detach-role-policy \
              --role-name ${{ env.ROLE_NAME }} \
              --policy-arn arn:aws:iam::$ACCOUNT_ID:policy/${{ env.API_POLICY_NAME }} || echo "API Gateway policy not attached"
            
            echo "✅ IAM role policies detached"
          else
            echo "ℹ️ IAM role not found, skipping policy detachment..."
          fi

      - name: Delete IAM Role
        run: |
          echo "🗑️ Deleting IAM role: ${{ env.ROLE_NAME }}"
          if aws iam get-role --role-name ${{ env.ROLE_NAME }} >/dev/null 2>&1; then
            aws iam delete-role --role-name ${{ env.ROLE_NAME }}
            echo "✅ IAM role deleted successfully"
          else
            echo "ℹ️ IAM role not found, skipping..."
          fi

      - name: Delete IAM Policy
        run: |
          echo "🗑️ Deleting IAM policy: ${{ env.API_POLICY_NAME }}"
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          POLICY_ARN="arn:aws:iam::$ACCOUNT_ID:policy/${{ env.API_POLICY_NAME }}"
          
          if aws iam get-policy --policy-arn $POLICY_ARN >/dev/null 2>&1; then
            # Delete all policy versions first
            aws iam list-policy-versions --policy-arn $POLICY_ARN --query 'Versions[?IsDefaultVersion==`false`].VersionId' --output text | tr '\t' '\n' | while read version; do
              if [ ! -z "$version" ]; then
                aws iam delete-policy-version --policy-arn $POLICY_ARN --version-id $version || echo "Failed to delete version $version"
              fi
            done
            
            # Delete the policy
            aws iam delete-policy --policy-arn $POLICY_ARN
            echo "✅ IAM policy deleted successfully"
          else
            echo "ℹ️ IAM policy not found, skipping..."
          fi

      - name: Delete S3 IAM Policy
        run: |
          echo "🗑️ Deleting S3 IAM policy: ${{ env.S3_POLICY_NAME }}"
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          S3_POLICY_ARN="arn:aws:iam::$ACCOUNT_ID:policy/${{ env.S3_POLICY_NAME }}"
          
          if aws iam get-policy --policy-arn $S3_POLICY_ARN >/dev/null 2>&1; then
            # Delete all policy versions first
            aws iam list-policy-versions --policy-arn $S3_POLICY_ARN --query 'Versions[?IsDefaultVersion==`false`].VersionId' --output text | tr '\t' '\n' | while read version; do
              if [ ! -z "$version" ]; then
                aws iam delete-policy-version --policy-arn $S3_POLICY_ARN --version-id $version || echo "Failed to delete version $version"
              fi
            done
            
            # Delete the policy
            aws iam delete-policy --policy-arn $S3_POLICY_ARN
            echo "✅ S3 IAM policy deleted successfully"
          else
            echo "ℹ️ S3 IAM policy not found, skipping..."
          fi

      - name: Cleanup Summary
        run: |
          echo "🎉 Cleanup completed!"
          echo "📋 Resources cleaned up:"
          echo "   - Lambda Function: ${{ env.FUNCTION_NAME }}"
          echo "   - Lambda Permissions: API Gateway invoke permissions"
          echo "   - API Gateway: ${{ env.API_GATEWAY_NAME }}"
          echo "   - IAM Role: ${{ env.ROLE_NAME }}"
          echo "   - IAM Policy: ${{ env.API_POLICY_NAME }}"
          echo "   - S3 IAM Policy: ${{ env.S3_POLICY_NAME }}"
          echo ""
          echo "💡 To redeploy, run the main deployment workflow or use:"
          echo "   ./create_deployment_package.sh && aws lambda create-function ..."
